"use client";

import { usePathname } from "next/navigation";

type PageKey = "services" | "coverage" | "standards" | "carriers" | "about" | "contact";

const content = {
  en: {
    nav: [["Services","services"],["Coverage","coverage"],["Standards","standards"],["Carriers","carriers"],["About","about"]],
    cta: "Request a Quote",
    pages: {
      services: { kicker:"DRAYAGE SERVICES", title:"Port-to-warehouse execution managed as one operation.", intro:"PortLink coordinates the full container move across terminals, motor carriers, warehouses, documents, and exceptions.", cards:[["Terminal coordination","Release and hold checks, LFD monitoring, pickup appointments, and terminal-specific planning."],["Pre-pull and storage planning","Early movement and staging options reviewed around free time, congestion, and delivery requirements."],["Warehouse delivery","Live unload, drop, appointment, and receiving coordination based on facility requirements."],["Equipment planning","Container type, weight, chassis, overweight, and special handling requirements reviewed before dispatch."],["Empty return control","Return location, cutoff, equipment instructions, and EIR documentation tracked through closeout."],["Document and charge review","POD, EIR, timestamps, photos, signatures, and available accessorial support organized by shipment."]], noteTitle:"Service scope is confirmed by lane.", note:"Terminal, ZIP code, weight, equipment, appointment pattern, and timing all affect service availability and pricing." },
      coverage: { kicker:"NY/NJ PORT COVERAGE", title:"Focused lanes. Better local control.", intro:"Our primary operating corridor connects the NY/NJ port complex with warehouse markets across New Jersey, Eastern Pennsylvania, and the New York metro area.", cards:[["Port Newark / Elizabeth","Core terminal and port-area coverage."],["APM Terminals","Pickup planning subject to release and appointment conditions."],["Maher Terminals","Container movement coordinated by lane and delivery requirement."],["PNCT","Terminal-specific pickup and equipment planning."],["GCT Bayonne","Coverage reviewed by shipment and delivery market."],["Warehouse corridors","North and Central New Jersey, Lehigh Valley, Eastern Pennsylvania, and select New York metro lanes."]], noteTitle:"Lane review before commitment.", note:"Coverage is confirmed using terminal, delivery ZIP, container weight, unload method, timing, and empty-return requirements." },
      standards: { kicker:"OPERATING STANDARDS", title:"Defined milestones, documented exceptions, clear ownership.", intro:"Professional drayage requires more than finding available capacity. Each move needs a repeatable operating sequence and an accountable escalation path.", cards:[["Order readiness","Required shipment, terminal, delivery, and equipment information collected before assignment."],["Carrier qualification","Executing motor-carrier capacity selected according to authority, insurance, equipment, and lane requirements."],["Milestone discipline","Pickup, out-gate, arrival, delivery, and empty-return updates organized around the shipment record."],["Document control","POD and EIR records requested and associated with the correct move."],["Exception escalation","Holds, appointment problems, delays, and receiving issues routed to the operating contact."],["Accessorial support","Available timestamps, photos, signatures, terminal documents, and charge details retained for review."]], noteTitle:"No unsupported performance claims.", note:"Service expectations and reporting are established during onboarding and should be measured using actual shipment records." },
      carriers: { kicker:"CARRIER NETWORK", title:"A professional operating relationship for qualified capacity.", intro:"PortLink works with compliant motor carriers and qualified owner-operators who value clear dispatch, responsive communication, and clean documentation.", cards:[["Clear dispatch","Shipment scope, terminal, delivery, timing, and document requirements provided before acceptance."],["Compliance review","Authority, insurance, W-9, agreements, driver, vehicle, and applicable port credentials reviewed."],["Operating updates","Required milestones and exception communication defined by shipment."],["Document expectations","POD, EIR, receipts, and accessorial support submitted promptly."],["Performance history","Reliability, communication, document quality, and exception handling inform future assignment."],["Long-term opportunity","Consistent execution can support recurring lanes and deeper operating relationships."]], noteTitle:"Interested in joining the network?", note:"Use the contact page and select Carrier Partnership. Do not send sensitive identity documents through the public form." },
      about: { kicker:"ABOUT PORTLINK", title:"A managed operating layer for NY/NJ drayage.", intro:"PortLink is being built around a simple principle: customers should not have to coordinate a terminal, a dispatcher, a driver, a warehouse, and a stack of documents on their own.", cards:[["Local focus","NY/NJ port drayage and surrounding warehouse corridors before broader geographic expansion."],["One operating window","A single point for quote coordination, execution status, documents, and exceptions."],["Qualified capacity","Motor-carrier capacity selected by lane, operating requirement, and compliance status."],["Cross-border understanding","Processes designed for teams managing U.S. freight from another country or time zone."],["Documented operations","Shipment records structured around milestones, supporting documents, and charge review."],["Technology roadmap","Customer, carrier, and driver tools designed to improve visibility without replacing operating accountability."]], noteTitle:"Corporate information should remain verifiable.", note:"Legal entity details, authority status, insurance, physical address, and contractual role should be published only after they are confirmed." },
      contact: { kicker:"CONTACT", title:"Start with the lane details.", intro:"Share enough information for a responsible operating review. A quote should reflect the actual terminal, delivery requirement, equipment, timing, and risk.", cards:[["Shipment","Container number if available, steamship line, terminal, and availability timing."],["Delivery","Warehouse address or ZIP code, receiving hours, appointment rules, live unload or drop."],["Equipment","Container size, gross weight, overweight status, chassis, and special requirements."],["Volume","One-time move, expected weekly or monthly volume, and seasonality."],["Commercial","Billing company, desired payment terms, and accessorial approval contact."],["Reply","Contact name, company email, phone number, and preferred response time."]], noteTitle:"operations@portlink.com", note:"Email the operating team with the subject “Drayage Quote Request.” Sensitive documents should be exchanged through an approved secure method after contact is established." }
    }
  },
  zh: {
    nav: [["拖柜服务","services"],["服务区域","coverage"],["运营标准","standards"],["车队合作","carriers"],["关于我们","about"]],
    cta: "提交询价",
    pages: {
      services: { kicker:"拖柜服务", title:"从码头到仓库，由一个运营窗口统一推进。", intro:"PortLink协调码头、承运车队、司机、收货仓、文件与异常，让每票柜子的责任和进度更加清楚。", cards:[["码头协调","核查放行与Hold、关注LFD、安排提柜预约并处理码头要求。"],["Pre-pull与暂存","根据免费期、码头拥堵和送货时间，核查提前提柜与暂存方案。"],["仓库交付","协调Live unload、Drop、送仓预约及收货要求。"],["设备安排","提前核查柜型、重量、底盘、超重及特殊操作需求。"],["空柜归还","跟进还空地点、截止时间、设备指示及EIR文件。"],["文件与费用","按柜整理POD、EIR、时间、照片、签字及附加费依据。"]], noteTitle:"具体服务需要按线路确认", note:"码头、送货邮编、重量、柜型、卸货方式和时间都会影响可执行性与报价。" },
      coverage: { kicker:"纽约／新泽西港覆盖", title:"线路越集中，执行控制越扎实。", intro:"目前重点连接纽约／新泽西港主要码头与新泽西、宾州东部和纽约都会区仓库。", cards:[["Port Newark／Elizabeth","核心港区与周边线路。"],["APM Terminals","根据放行、预约和送仓要求安排。"],["Maher Terminals","按具体柜况和送货要求核查。"],["PNCT","结合码头规则、设备与线路安排。"],["GCT Bayonne","按柜型、重量与送货区域确认。"],["主要仓库走廊","新泽西中北部、Lehigh Valley、宾州东部及部分纽约都会区。"]], noteTitle:"承诺前先核查线路", note:"需要确认码头、送货邮编、柜重、卸货方式、时间和还空要求。" },
      standards: { kicker:"运营标准", title:"节点明确、异常留痕、责任清楚。", intro:"专业拖柜不能只靠临时找车。每票运输都应有统一流程、明确节点和异常升级机制。", cards:[["资料完整","派单前收集柜号、码头、送货、设备和时间要求。"],["运力合规","根据Authority、保险、设备、司机和线路要求选择承运方。"],["节点更新","围绕提柜、出闸、到仓、送达和还空整理状态。"],["文件归档","POD、EIR及相关收据对应到正确柜子。"],["异常升级","Hold、预约、延误和收货异常转给指定运营联系人。"],["附加费依据","保存可用时间记录、照片、签字、码头文件和收费明细。"]], noteTitle:"不使用没有依据的业绩数字", note:"服务目标与汇报方式在合作启动时确认，并通过真实运输记录持续衡量。" },
      carriers: { kicker:"车队合作", title:"为合规、稳定的运力建立长期合作关系。", intro:"PortLink欢迎重视清晰派单、及时沟通和规范文件的承运车队与合规Owner Operator。", cards:[["派单清楚","接单前提供码头、送仓、时间及文件要求。"],["合规审核","核查Authority、保险、W-9、合同、司机、车辆及港区资质。"],["节点要求","按任务要求更新关键进度并及时报告异常。"],["文件标准","及时提交POD、EIR、收据和附加费依据。"],["履约记录","准时、沟通、文件和异常处理会影响后续派单。"],["长期货量","表现稳定的合作方有机会进入固定线路和长期合作。"]], noteTitle:"申请加入车队网络", note:"通过联系页面选择车队合作。请勿通过公开表单发送身份证件等敏感材料。" },
      about: { kicker:"关于PORTLINK", title:"连接纽约港需求与合规本地运力的运营平台。", intro:"我们的出发点很简单：客户不应当自己追着码头、调度、司机、仓库和文件反复沟通。", cards:[["区域聚焦","先做好纽约／新泽西港及周边仓库线路，再逐步扩大区域。"],["统一窗口","报价、执行进度、文件与异常由一个窗口协调。"],["合规运力","根据线路、操作要求和合规状态选择实际承运方。"],["理解跨境客户","适配人在中国、货在美国以及跨时区管理的团队。"],["过程留痕","按柜记录节点、文件、异常与费用审核。"],["系统规划","逐步建设客户、车队和司机工具，提高可视化但不替代运营责任。"]], noteTitle:"企业信息必须真实可核查", note:"公司主体、Authority、保险、地址和合同角色确认后再正式对外发布。" },
      contact: { kicker:"联系我们", title:"先把线路资料说清楚。", intro:"完整资料才能形成负责任的报价。请尽量提供码头、送货要求、设备、时间和货量。", cards:[["柜子资料","柜号（如有）、船公司、码头和预计可提时间。"],["送货要求","仓库地址或邮编、收货时间、预约规则、Live unload或Drop。"],["设备与重量","柜型、毛重、是否超重、底盘和特殊要求。"],["预计货量","单票、每周或每月柜量以及旺淡季。"],["商务信息","付款公司、期望账期和附加费确认人。"],["回复方式","联系人、公司邮箱、电话及希望回复时间。"]], noteTitle:"operations@portlink.com", note:"邮件标题请写“拖柜询价”。建立联系后，敏感文件应通过双方确认的安全方式交换。" }
    }
  }
};

export default function CorporateSubpage() {
  const pathname = usePathname();
  const zh = pathname.startsWith("/zh/");
  const lang = zh ? content.zh : content.en;
  const slug = (pathname.split("/").filter(Boolean).at(-1) || "about") as PageKey;
  const page = lang.pages[slug] || lang.pages.about;
  const prefix = zh ? "/zh" : "";
  return <main className="subpage">
    <header className="sub-header"><a className="logo" href={prefix || "/"}><span>P</span><b>PortLink</b></a><nav>{lang.nav.map(([label,path]) => <a key={path} href={`${prefix}/${path}`}>{label}</a>)}</nav><a className="solid small" href={`${prefix}/contact`}>{lang.cta}</a></header>
    <section className="sub-hero"><div><p className="kicker">{page.kicker}</p><h1>{page.title}</h1><p>{page.intro}</p></div></section>
    <section className="sub-grid">{page.cards.map(([h,p],i) => <article key={h}><span>0{i+1}</span><h2>{h}</h2><p>{p}</p></article>)}</section>
    <section className="sub-note"><p className="kicker">PORTLINK</p><h2>{page.noteTitle}</h2><p>{page.note}</p>{slug === "contact" && <a className="solid" href="mailto:operations@portlink.com">operations@portlink.com</a>}</section>
    <footer><div className="footer-brand"><a className="logo" href={prefix || "/"}><span>P</span><b>PortLink</b></a><p>{zh ? "纽约／新泽西港全流程拖柜。" : "Managed NY/NJ port drayage."}</p></div><div className="footer-col"><b>{zh ? "服务区域" : "SERVICE AREA"}</b><span>New Jersey</span><span>Eastern Pennsylvania</span><span>New York Metro</span></div><div className="footer-col"><b>{zh ? "运营联系" : "OPERATIONS"}</b><a href="mailto:operations@portlink.com">operations@portlink.com</a></div><div className="footer-bottom"><span>© 2026 PortLink. All rights reserved.</span><span>{zh ? "具体服务及价格以线路审核为准。" : "Service and pricing subject to lane review."}</span></div></footer>
  </main>;
}
